.circleci/config.yml
.github/workflows/pylint.yml
.gitignore
ansible_deploy/command_line.py
tests/pylintrc

create_workdir, set_logging, parse_options functions added

basic functions added

---

.circleci/config.yml
.github/workflows/pylint.yml
etc/hooks/setup_work_dir.sh
tests/02-checkrun.sh

Check/merge this one before working on tests, I think it's good foundation for real run test

Add basic testing of run command without --dry

---

ansible_deploy/command_line.py
setup.py

We create a lock file based on that config, so it can contain '/' on
Linux.

Allow inventory to be given as full path not just a file

---

.circleci/config.yml
ansible_deploy/command_line.py
setup.py

This is to give a script an opportunity to check if the location is
correct, for instance if shell cwd will get changed by .profile/.bashrc

Pass workdir as environment variable to setup_hook

---

ansible_deployer/command_line.py
tests/01-test_argument_parsing.sh

Improve subcommand error message

---

ansible_deployer/command_line.py
setup.py

This is to communicete to user, so parsing should be easy.

Use print instead of info for print

---

ansible_deployer/command_line.py
etc/acl.yaml
etc/schema/acl.yaml
etc/schema/tasks.yaml
etc/tasks.yaml
tests/files/etc/tasks_error_hook.yaml
tests/files/etc/tasks_exit_hook.yaml

Add acl config

---

ansible_deployer/command_line.py

Since we're changing CWD inside ansible-deployer we need to translate
the relative path to absolute parsing options

Support relative path for --conf-dir

---

ansible_deployer/command_line.py
tests/02-checkrun.sh

Add --keep-locked option

---

ansible_deployer/command_line.py
tests/01-test_argument_parsing.sh
tests/02-checkrun.sh

Add show subcommand

---

setup.py
source/main.py

Add --version flag

---

.circleci/config.yml
etc/infra.yaml
setup.py
source/main.py
source/modules/configs/schema.py
source/modules/misc.py
source/modules/runners/run.py
source/modules/validators/validate.py
tests/02a-checkrun_with_self_setup.sh
tests/testing_lib.sh

Add --local-checkout option

---

setup.py
source/modules/validators/validate.py

Update not_supported lists in option validation

---

source/modules/outputs/logging.py

Bugfix commit a2c68e160ccfd09c12f7f4dba8b59c3e2595a321
fixing issue #128

Remove redundant setLevel for console_handler in logging

---

setup.py
source/modules/runners/run.py

Bugfix reassign_commit_and_workdir()

---

setup.py
source/main.py
source/modules/globalvars.py
source/modules/outputs/logging.py
source/modules/validators/validate.py

Add basic colouring

---

.circleci/config.yml
setup.py
source/main.py
tests/02a-checkrun_with_self_setup.sh

bugfix 4c75723b0071370abe3ceb4e07f5a8d34fc71d54

bugfix setup hook still running when --self-setup on

---

setup.py
source/main.py
source/modules/database/creator.py
source/modules/database/schema.py
source/modules/database/writer.py
source/modules/runners/run.py
tests/pylintrc

Sqlite database implementation

---

source/modules/database/schema.py
source/modules/database/writer.py
source/modules/outputs/formatting.py
source/modules/runners/run.py

bugfix 75cf653beb80ebd5047032cda3db3e4660a20d5b

Db record parsing fixes

---

setup.cfg
source/main.py
source/modules/database/schema.py
source/modules/outputs/__init__.py
source/modules/outputs/blocks.py
source/modules/outputs/formatting.py
source/modules/runners/run.py
source/plugins/log_plays_adjusted.py
source/plugins/sqlite_deployer.py
tests/02a-checkrun.sh
tests/02a-checkrun_short.sh

More plugin and output fixes
